# 실행 모드 설정: 'train' (처음부터 학습), 'resume' (중단된 학습 재개), 'continue' (학습 후 추가 학습)
# 파일 보고 필요한 파라미터에 따라 주석하여 사용
mode: 'train'  # 'train', 'resume', 'continue' 중 하나를 설정

# 모델 설정
model: 'yolo11m.pt'  # 학습에 사용할 모델 가중치 파일 경로

# 데이터셋 설정
data: 'datasets/data.yaml'  # 데이터셋 설정 파일 경로 (.yaml 형식)

# 학습 파라미터
epochs: 100  # 학습 에폭 수 (전체 데이터셋을 몇 번 반복할지)
batch: 64  # 배치 크기 (한 번에 학습에 사용할 데이터 개수)
imgsz: 640  # 이미지 크기 (모델 입력 이미지 크기, 예: 640x640)

# 조기 종료 설정
patience: 20  # 조기 종료를 위한 patience (지정한 에폭 동안 성능 향상이 없으면 학습 중단)

# 장치 설정
device: 'cpu'  # 사용 장치 설정 (단일 GPU: '0', 다중 GPU: [0, 1], cpu : 'cpu')

# 옵티마이저 설정
optimizer: 'AdamW'  # 옵티마이저 종류 (예: 'SGD', 'Adam', 'AdamW')

# 기타 설정
seed: 42  # 랜덤 시드 설정 (재현성을 위해 고정된 시드 사용)
save: true  # 체크포인트 저장 여부 (모델 가중치를 주기적으로 저장)
val: true  # 검증 데이터 사용 여부 (True일 경우 매 에폭마다 검증 수행)
momentum: 0.9  # 모멘텀 값 (주로 SGD와 함께 사용됨)

# 학습률 설정
cos_lr: true  # Cosine 학습률 스케줄러 사용 여부
amp: true  # 자동 혼합 정밀도 사용 (메모리 사용 절감 및 속도 향상)

# 추가 학습 파라미터
pretrained: true  # 사전 학습된 가중치 사용 여부
lr0: 0.005  # 초기 학습률 (학습 시작 시 학습률 설정)
lrf: 0.1  # 최종 학습률 비율 (학습이 끝날 때 학습률 감소 비율)
weight_decay: 0.0001  # 가중치 감쇠 값 (모델이 과적합되지 않도록 정규화 역할)
warmup_epochs: 5  # 워밍업 에폭 수 (초기 학습률 증가 단계)
