# config.yaml

model: 'yolo11m.pt'  # 모델 경로
data: 'datasets/data.yaml'  # 데이터셋 설정 파일 경로
epochs: 100  # 학습 에폭 수
batch: 64  # 배치 크기
imgsz: 640  # 이미지 크기
patience: 20  # 조기 종료 patience
device: [0, 1]  # 사용 장치 (멀티 GPU)
optimizer: 'AdamW'  # 옵티마이저
seed: 42  # 랜덤 시드
save: true  # 체크포인트 저장
val: true  # 검증 사용
momentum: 0.9  # 모멘텀 값
cos_lr: true  # cosine 학습률 사용
amp: true  # 자동 혼합 정밀도 사용

# 추가 학습 파라미터
pretrained: true  # 사전 학습 가중치 사용
lr0: 0.005  # 초기 학습률
lrf: 0.1  # 최종 학습률 비율
weight_decay: 0.0001  # 가중치 감쇠
warmup_epochs: 5  # 워밍업 에폭 수
